INSERT INTO inventory_items (id, name, sku, quantity, price) VALUES ('1', 'iPhone 15', 'IP15-128-BLK', 10, 799.0);
INSERT INTO inventory_items (id, name, sku, quantity, price) VALUES ('2', 'Samsung S24', 'SS24-256-GRY', 15, 899.0);
INSERT INTO inventory_items (id, name, sku, quantity, price) VALUES ('3', 'MacBook Air M3', 'MBA-M3-13-8-256', 5, 1099.0);
INSERT INTO inventory_items (id, name, sku, quantity, price) VALUES ('4', 'AirPods Pro 2', 'APP2-WHT', 20, 249.0);
INSERT INTO inventory_items (id, name, sku, quantity, price) VALUES ('5', 'iPad Pro M4', 'IPP-M4-11-256-SLV', 8, 999.0);
INSERT INTO inventory_items (id, name, sku, quantity, price) VALUES ('6', 'Sony WH-1000XM5', 'SNY-XM5-BLK', 12, 349.0);
INSERT INTO inventory_items (id, name, sku, quantity, price) VALUES ('7', 'Nintendo Switch OLED', 'NSW-OLED-WHT', 25, 349.99);
INSERT INTO inventory_items (id, name, sku, quantity, price) VALUES ('8', 'Dell XPS 15', 'DELL-XPS15-9530', 3, 1899.0);
INSERT INTO inventory_items (id, name, sku, quantity, price) VALUES ('9', 'Logitech MX Master 3S', 'LOGI-MXM3S-GRY', 30, 99.0);
INSERT INTO inventory_items (id, name, sku, quantity, price) VALUES ('10', 'Kindle Paperwhite', 'KNDL-PW-16GB', 18, 149.0);
